forward_dynamics:
  _target_: exp.utils.replicate
  num: ${shared.num_meta_levels}
  obj:
    _target_: exp.trainers.forward_dynamics.StackedHiddenFDTrainerExplicitTarget.create_buffer
    max_size: 1000 #  10 fps 100 secs

policy:
  _target_: exp.trainers.ppo_policy.PPOStackedHiddenPiVTrainer.create_buffer
  max_size: 1000 # 10 fps 100 secs
