forward_dynamics:
  _target_: exp.trainers.forward_dynamics.HiddenStateFDTrainer.create_buffer
  max_size: 1000 #  10 fps 100 secs

policy:
  _target_: exp.trainers.ppo_policy.PPOHiddenStatePiVTrainer.create_buffer
  max_size: 1000 # 10 fps 100 secs
