services:
  dev:
    container_name: pamiq-curiosity-exp_${USER}
    image: pamiq-curiosity-exp:${USER}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - pamiq-curiosity-exp:/workspace
      - uv_cache:/root/.cache/uv
      - pip_cache:/root/.cache/pip
      - pre-commit_cache:/root/.cache/pre-commit
      # Time zone
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Log dir
      - ${LOG_DIR:-./logs}:/workspace/logs
    environment:
      - PYRIGHT_PYTHON_FORCE_VERSION=latest
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    working_dir: /workspace
    command: /bin/bash
    stop_grace_period: 0s

volumes:
  pamiq-curiosity-exp:
    name: pamiq-curiosity-exp-${USER}
  uv_cache:
  pip_cache:
  pre-commit_cache:
