_target_: exp.trainers.forward_dynamics.StackedHiddenFDTrainer
partial_optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
seq_len: 256
max_samples: 32
imagination_length:  ${shared.max_imagination_steps}
min_new_data_count: 128
