# @package interaction.agent.curiosity

_target_: exp.agents.curiosity.meta.MetaCuriosityAgent
num_meta_levels: ${shared.num_meta_levels}
surprisal_coefficients_method: "maximize_top"
device: ${shared.device}
dtype: ${shared.dtype}
