# @package interaction.agent.curiosity

_target_: exp.agents.curiosity.meta.MetaCuriosityAgent
num_meta_levels: 2
surprisal_coefficients_method: "minimize_to_maximize"
device: ${shared.device}
dtype: ${shared.dtype}
