# @package interaction.agent.curiosity

_target_: exp.agents.curiosity.meta.MetaCuriosityAgent
surprisal_coefficients:
  _target_: exp.agents.curiosity.meta.create_surprisal_coefficients
  method: "maximize_top"
  num: ${shared.num_meta_levels}
device: ${shared.device}
dtype: ${shared.dtype}
