policy_value:
  _target_: exp.models.latent_policy.create_hierarchical
  obs_info: ${models.forward_dynamics.obs_info}

  action_info:
    _target_: exp.models.utils.ActionInfo
    choices:
      _target_: hydra.utils.get_object
      path: exp.envs.vrchat.OSC_ACTION_CHOICES
    dim: 8

  action_dims:
    _target_: exp.int_seq.arithmetic
    start: 1024
    diff: 2
    num: ${shared.num_hierarchical_layers}

  latent_obs_dims: ${models.forward_dynamics.latent_obs_dims}

  latent_action_dims: ${.core_model_dims}

  core_model_dims:
    _target_: exp.int_seq.arithmetic
    start: 1024
    diff: 2
    num: ${shared.num_hierarchical_layers}

  core_models:
    _target_: exp.models.components.qgru.create_multiple
    depth: 8
    dim_list: ${..core_model_dims}
    dim_ff_hidden_scale: 4
    dropout: 0.1

  device: ${shared.device}
  dtype: ${shared.dtype}


forward_dynamics:
  _target_: exp.models.latent_fd.create_hierarchical
  obs_info:
    _target_: exp.models.utils.ObsInfo
    dim: 128 # Same as JEPA instantiattion.
    num_tokens:
      _target_: exp.models.jepa.compute_image_jepa_output_patch_count
      image_size:
        - ${shared.image.height}
        - ${shared.image.width}
      patch_size: 12 # Same as JEPA Instantiation
      output_downsample: 3 # Same as JEPA Instantiation
    dim_hidden: 1024

  latent_action_dims: ${models.policy_value.latent_action_dims}

  latent_obs_dims: ${.core_model_dims}

  core_model_dims:
    _target_: exp.int_seq.arithmetic
    start: 1024
    diff: 2
    num: ${shared.num_hierarchical_layers}

  core_models:
    _target_: exp.models.components.qgru.create_multiple
    depth: 8
    dim_list: ${..core_model_dims}
    dim_ff_hidden_scale: 4
    dropout: 0.1

  device: ${shared.device}
  dtype: ${shared.dtype}
