policy_value:
  _target_: exp.models.latent_policy.create_hierarchical
  obs_info: ${models.forward_dynamics.obs_info}

  action_info:
    _target_: exp.models.utils.ActionInfo
    choices:
      _target_: hydra.utils.get_object
      path: exp.envs.vrchat.OSC_ACTION_CHOICES
    dim: 8

  action_dims:
    _target_: exp.int_seq.same
    value: 1024
    num: ${shared.num_hierarchical_layers}

  latent_obs_dims: ${models.forward_dynamics.latent_obs_dims}

  latent_action_dims: ${.core_model_dims}

  core_model_dims:
    _target_: exp.int_seq.same
    value: ${..core_models.obj.dim}
    num: ${shared.num_hierarchical_layers}

  core_models:
    _target_: exp.utils.replicate
    obj:
      _target_: exp.models.components.QLSTM
      dim: 1024
      dim_ff_hidden: ${python.eval:"${.dim} * 4"}
      depth: 8
      dropout: 0.1
    num: ${shared.num_hierarchical_layers}

  device: ${shared.device}
  dtype: ${shared.dtype}


forward_dynamics:
  _target_: exp.models.latent_fd.create_hierarchical
  obs_info:
    _target_: exp.models.utils.ObsInfo
    dim: 128 # Same as JEPA instantiattion.
    num_tokens:
      _target_: exp.models.jepa.compute_image_jepa_output_patch_count
      image_size:
        - ${shared.image.height}
        - ${shared.image.width}
      patch_size: 12 # Same as JEPA Instantiation
      output_downsample: 3 # Same as JEPA Instantiation
    dim_hidden: ${..dim}

  latent_action_dims: ${models.policy_value.latent_action_dims}

  latent_obs_dims: ${.core_model_dims}

  core_model_dims:
    _target_: exp.int_seq.same
    value: ${..core_models.obj.dim}
    num: ${shared.num_hierarchical_layers}

  core_models:
    _target_: exp.utils.replicate
    obj:
      _target_: exp.models.components.QLSTM
      dim: 1024
      dim_ff_hidden: ${python.eval:"${.dim} * 4"}
      depth: 8
      dropout: 0.1
    num: ${shared.num_hierarchical_layers}

  device: ${shared.device}
  dtype: ${shared.dtype}
