# StackedHidden Models
defaults:
  - stacked_hiddens

policy_value:
  model:
    core_model:
      dim: 2048
      depth: 12

forward_dynamics:
  model:
    core_model:
      dim: 2048
      depth: 12
