disable_jepa: null
fd_policy_value:
  _target_: pamiq_core.torch.TorchTrainingModel
  has_inference_model: true
  device: ${shared.device}
  dtype: ${shared.dtype}
  inference_procedure:
    _target_: hydra.utils.get_method
    path: exp.models.fd_policy.TTTFDPiV.forward_with_no_len
  model:
    _target_: exp.models.fd_policy.TTTFDPiV
    obs_dim_hidden: 1024
    action_info:
      _target_: exp.models.utils.ActionInfo
      choices:
        _target_: hydra.utils.get_object
        path: exp.envs.vrchat.OSC_ACTION_CHOICES
      dim: 8
    external_action_dim: 256
    attention_dim: 64
    surprisal_dim: 64
    value_dim: 64
    internal_action_dim: 256
    body_state_dim: 1
    dim: ${.core_model.dim}
    obs_encoder:
      _target_: exp.models.components.cnn_encoder.CNNEncoder
      input_channels: ${shared.image.channels}
      input_height: ${shared.image.height}
      input_width: ${shared.image.width}
      output_dim: ${..obs_dim_hidden}
    obs_time_mixer:
      _target_: exp.models.components.qgru.QGRU
      dim: 1024
      dim_hidden: 2048
      depth: 8
      dropout: 0.1
      is_weak: true
    core_model:
      _target_: exp.models.components.ttt.TTT
      dim: 1024
      dim_hidden: 4096
      depth: 16
      num_head: 32
      base_lr: [0.01, 0.1]
      chunk_size: 64
      dropout: 0.1
    surprisal_shape:
      - ${..core_model.depth}
      - ${..core_model.num_head}
      - ${python.eval:"${..core_model.dim} // ${..core_model.num_head}"}
